// examples/react-counter/src/Counter.tsx
import React, { useState } from "react"
import { useXSkill } from "@x-skills-for-ai/react"

export function Counter() {
  const [count, setCount] = useState(0)

  // Register increment skill
  useXSkill({
    id: "increment",
    description: "Increase counter",
    handler: () => setCount(c => c + 1)
  })

  // Register decrement skill
  useXSkill({
    id: "decrement",
    description: "Decrease counter",
    handler: () => setCount(c => c - 1)
  })

  return (
    <div>
      <h2>Counter: {count}</h2>
      <button onClick={() => setCount(c => c + 1)}>Increment</button>
      <button onClick={() => setCount(c => c - 1)}>Decrement</button>
    </div>
  )
}

// examples/svelte/svelte-counter/src/Counter.svelte
<script lang="ts">
  import { useXSkill } from '@x-skills-for-ai/svelte'
  import { writable } from 'svelte/store'

  let count = writable(0)

  useXSkill({
    id: 'increment',
    description: 'Increase counter',
    handler: async () => {
      count.update(c => c + 1)
    }
  })

  useXSkill({
    id: 'decrement',
    description: 'Decrease counter',
    handler: async () => {
      count.update(c => c - 1)
    }
  })

  function inc() {
    count.update(c => c + 1)
  }

  function dec() {
    count.update(c => c - 1)
  }
</script>

<h2 data-testid="count">Counter: {$count}</h2>
<button on:click={inc}>Increment</button>
<button on:click={dec}>Decrement</button>
