// examples/svelte/svelte-counter/src/Counter.svelte
<script lang="ts">
  import { useXSkill } from '@x-skills-for-ai/svelte'
  import { writable } from 'svelte/store'

  let count = writable(0)

  useXSkill({
    id: 'increment',
    description: 'Increase counter',
    handler: async () => {
      count.update(c => c + 1)
    }
  })

  useXSkill({
    id: 'decrement',
    description: 'Decrease counter',
    handler: async () => {
      count.update(c => c - 1)
    }
  })

  function inc() {
    count.update(c => c + 1)
  }

  function dec() {
    count.update(c => c - 1)
  }
</script>

<h2 data-testid="count">Counter: {$count}</h2>
<button on:click={inc}>Increment</button>
<button on:click={dec}>Decrement</button>

// examples/angular/angular-counter/src/app/counter/counter.component.ts
import { Component, signal } from '@angular/core';
import { XSkillDefinition } from '@x-skills-for-ai/core';
import { XSkillDirective } from '@x-skills-for-ai/angular';

@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [XSkillDirective],
  templateUrl: './counter.component.html',
  styleUrl: './counter.component.css'
})
export class CounterComponent {
  count = signal(0);

  incrementDef: XSkillDefinition = {
    id: 'increment',
    description: 'Increase counter',
    handler: async () => {
      this.count.update(c => c + 1);
    }
  };

  decrementDef: XSkillDefinition = {
    id: 'decrement',
    description: 'Decrease counter',
    handler: async () => {
      this.count.update(c => c - 1);
    }
  };
}

<div style="display: none" xSkill [xSkill]="incrementDef"></div>
<div style="display: none" xSkill [xSkill]="decrementDef"></div>
<h2 data-testid="count">Counter: {{ count() }}</h2>
<button (click)="count.update(c => c + 1)">Increment</button>
<button (click)="count.update(c => c - 1)">Decrement</button>
